name: Windows RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: RDP Hazirla
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Tunnel Baslat (Serveo - Aninda Baglanti)
      run: ssh -o StrictHostKeyChecking=no -R 0:localhost:3389 serveo.net
